---
get:
  summary: List applications
  description: Retrieves a list of all applications
  responses:
    '200':    # status code
      description: A JSON array of applications
      content:
        application/json:
          schema:
            $ref: '../schemas/Application.yaml'
    '401':
      $ref: '../components/responses/Unauthorized.yaml'
    '404':
      $ref: '../components/responses/NotFound.yaml'
