get:
  summary: Get a application
  description: Retrieves a single application
  parameters:
    - name: id
      in: query
      description: Unique id in the service provider
      required: true
      schema:
        type: string
        format: uuid
        example: 301ee8e6-b5d1-40b5-a27e-47611f803371
  responses:
    '200':    # status code
      description: a single application
      content:
        application/json:
          schema:
            $ref: '../schemas/Application.yaml'
    '401':
      $ref: '../components/responses/Unauthorized.yaml'
    '404':
      $ref: '../components/responses/NotFound.yaml'
post:
  summary: Create a application
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../schemas/Application.yaml'
  responses:
    '201':
      description: The application was created, the new application is returned
      content:
        application/json:
          schema:
            $ref: '../schemas/Application.yaml'
    '401':
      $ref: '../components/responses/Unauthorized.yaml'
    '404':
      $ref: '../components/responses/NotFound.yaml'
put:
  summary: Update a application
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../schemas/Application.yaml'
  responses:
    '200':
      description: The application was updated, the new application is returned
      content:
        application/json:
          schema:
            $ref: '../schemas/Application.yaml'
    '401':
      $ref: '../components/responses/Unauthorized.yaml'
    '404':
      $ref: '../components/responses/NotFound.yaml'
delete:
  summary: Deletes a application
  description: Deletes the application specified by the id
  parameters:
    - name: id
      in: query
      description: application ID
      required: true
      schema:
        type: string
        format: uuid
        example: 301ee8e6-b5d1-40b5-a27e-47611f803371
  responses:
    '200':    # status code
      description: OK
    '401':
      $ref: '../components/responses/Unauthorized.yaml'
    '404':
      $ref: '../components/responses/NotFound.yaml'
