openapi: 3.0.0
info:
  title: GuestApplication API
  description: This describes the REST interface to the guestapplication API
  version: 0.0.1
servers:
  - url: http://guest.test.eduid.nl/v1
    description: Public testing enviroment
  - url: http://guest.eduid.nl/v1
    description: Production enviroment
paths:
  /invite:
    $ref: './paths/invite.yaml'
  /role:
    $ref: './paths/role.yaml'
  /roles:
    $ref: './paths/roles.yaml'
  /guest:
    $ref: './paths/guest.yaml'
  /guests:
    $ref: './paths/guests.yaml'
  /user:
    $ref: './paths/user.yaml'
  /users:
    $ref: './paths/users.yaml'
