openapi: 3.0.0
info:
  title: GuestApplication API
  description: |
    This describes the REST interface to the invite-application API.
    # Design
    The arcitectural design for this application can be found [here](../archi/index.html)
  version: 0.0.1
servers:
  - url: http://invite.test.eduid.nl/v1
    description: Public testing enviroment
  - url: http://invite.eduid.nl/v1
    description: Production enviroment
paths:
  /invite:
    $ref: './paths/invite.yaml'
  /role:
    $ref: './paths/role.yaml'
  /roles:
    $ref: './paths/roles.yaml'
  /guest:
    $ref: './paths/guest.yaml'
  /guests:
    $ref: './paths/guests.yaml'
  /user:
    $ref: './paths/user.yaml'
  /users:
    $ref: './paths/users.yaml'
