name: make-doc

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  test-redoc:
    runs-on: ubuntu-latest
    name: Test openapi and generate html documentation
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: lint markdown file
        uses: nosborn/github-action-markdown-cli@v2.0.0
        with:
          files: .

      - name: Test api-specs with redoc-cli
        uses: seeebiii/redoc-cli-github-action@v10
        with:
          args: 'bundle specs/invite.yaml -t template.hbs -o docs/api/index.html'

      - name: check result
        run: |
          ls -al docs/api/
          test -f docs/api/index.html || (echo "Missing docs/index.html from previous step." && exit 1)

      - name: Commit files if the html has changed
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/api/index.html
          git diff-index --quiet HEAD || git commit -m "Update github page"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
